

services:
  web:
    build: .
    ports:
      - "127.0.0.1:8100:8100"
    depends_on:
      - db
    environment:
      PICCOLO_CONF: piccolo_conf
      GHOSTBIKE_DB_ENGINE: postgres
    volumes:
      - ./Ghostbike-Hamburg-Tabelle.json:/app/Ghostbike-Hamburg-Tabelle.json:ro
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ghostbikedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
